
<!-- <script src="{{url(dirTemaToko().'junotoys/assets/js/bootstrap.js')}}" type="text/javascript"></script> -->
{{HTML::script(dirTemaToko()."junotoys/assets/js/vendor/jquery/jquery.js")}}
{{HTML::script(dirTemaToko()."junotoys/assets/js/jquery.2.2.3.js")}}
{{HTML::script(dirTemaToko()."junotoys/assets/js/vendor/jquery/jquery-migrate.min.js")}}
{{HTML::script(dirTemaToko()."junotoys/assets/js/bootstrap.js")}}
{{HTML::script(dirTemaToko()."junotoys/assets/js/custom/custom.js")}}
{{HTML::script(dirTemaToko()."junotoys/assets/js/vendor/essgrid/lightbox.js")}}
{{HTML::script(dirTemaToko()."junotoys/assets/js/vendor/essgrid/jquery.themepunch.tools.min.js")}}
{{HTML::script(dirTemaToko()."junotoys/assets/js/vendor/essgrid/jquery.themepunch.essential.min.js")}}
{{HTML::script(dirTemaToko()."junotoys/assets/js/vendor/revslider/jquery.themepunch.revolution.min.js")}}
{{HTML::script(dirTemaToko()."junotoys/assets/js/vendor/revslider/extensions/revolution.extension.slideanims.min.js")}}
{{HTML::script(dirTemaToko()."junotoys/assets/js/vendor/revslider/extensions/revolution.extension.actions.min.js")}}
{{HTML::script(dirTemaToko()."junotoys/assets/js/vendor/revslider/extensions/revolution.extension.layeranimation.min.js")}}
{{HTML::script(dirTemaToko()."junotoys/assets/js/vendor/woo/add-to-cart.min.js")}}
{{HTML::script(dirTemaToko()."junotoys/assets/js/vendor/woo/woocommerce-add-to-cart.js")}}
{{HTML::script(dirTemaToko()."junotoys/assets/js/vendor/photostack/modernizr.min.js")}}
{{HTML::script(dirTemaToko()."junotoys/assets/js/vendor/woo/jquery.blockUI.min.js")}}
{{HTML::script(dirTemaToko()."junotoys/assets/js/vendor/woo/woocommerce.min.js")}}
{{HTML::script(dirTemaToko()."junotoys/assets/js/vendor/woo/jquery.cookie.min.js")}}
{{HTML::script(dirTemaToko()."junotoys/assets/js/vendor/woo/cart-fragments.min.js")}}
{{HTML::script(dirTemaToko()."junotoys/assets/js/vendor/superfish.js")}}
{{HTML::script(dirTemaToko()."junotoys/assets/js/custom/jquery/core.utils.js")}}
{{HTML::script(dirTemaToko()."junotoys/assets/js/custom/jquery/core.init.js")}}
{{HTML::script(dirTemaToko()."junotoys/assets/js/custom/jquery/theme.init.js")}}
{{HTML::script(dirTemaToko()."junotoys/assets/js/vendor/mediaelement/mediaelement-and-player.min.js")}}
{{HTML::script(dirTemaToko()."junotoys/assets/js/custom/jquery/theme.shortcodes.js")}}
{{HTML::script(dirTemaToko()."junotoys/assets/js/custom/jquery/core.messages.js")}}
{{HTML::script(dirTemaToko()."junotoys/assets/js/vendor/magnific/jquery.magnific-popup.min.js")}}
{{HTML::script(dirTemaToko()."junotoys/assets/js/vendor/grid.layout/grid.layout.min.js")}}
{{HTML::script(dirTemaToko()."junotoys/assets/js/vendor/swiper/swiper.min.js")}}
{{HTML::script(dirTemaToko()."junotoys/assets/js/vendor/ui/core.min.js")}}
{{HTML::script(dirTemaToko()."junotoys/assets/js/vendor/ui/widget.min.js")}}
{{HTML::script(dirTemaToko()."junotoys/assets/js/vendor/ui/tabs.min.js")}}
{{HTML::script(dirTemaToko()."junotoys/assets/js/vendor/ui/effect.min.js")}}
{{HTML::script(dirTemaToko()."junotoys/assets/js/vendor/ui/effect-fade.min.js")}}
{{HTML::script(dirTemaToko()."junotoys/assets/js/vendor/isotope/isotope.pkgd.min.js")}}
{{HTML::script(dirTemaToko()."junotoys/assets/js/vendor/woo/jquery.prettyPhoto.min.js?ver=3.1.6")}}
{{HTML::script(dirTemaToko()."junotoys/assets/js/vendor/woo/jquery.prettyPhoto.init.min.js")}}